Add shape tranformation docs
CAU-Kiel-Tech-Inf/socha-enduser-docs pull request #25
Opened 2020-10-08 19:42 UTC by niklasCarstensen

Du solltest noch mal drübersehen bevor das auf master gepusht wird

2020-10-08 19:48 UTC, niklasCarstensen commented
Ich hab auch die picture paths in dem ordner angepasst

2020-10-10 07:59 UTC, anarchuser requested changes
Ich habe ein paar optionale Änderungsvorschläge sowie ein bisschen Grammatik angemerkt; inhaltlich ist es aber soweit gut

2020-10-10 07:59 UTC, anarchuser commented on spiele/blokus/xml-dokumentation/zuege-senden.adoc
> +Bei `ROTATION` `MIRROR` wird der Spielstein zweimal um den Ursprung nach rechts gedreht, oder anders gesagt auf beiden Achsen invertiert.
Man könnte erwähnen, dass der Stein am Ursprung gespiegelt wird, dann haben die Schüler die Referenz zu `MIRROR`

2020-10-10 07:59 UTC, anarchuser commented on spiele/blokus/xml-dokumentation/zuege-senden.adoc
> +Auf dem vorigen Bild ist das resultat von `ROTATION` `LEFT` und  `FLIPPED` `true` zu sehen.
```suggestion
Auf dem vorigen Bild ist das Resultat von `ROTATION` `LEFT` und  `FLIPPED` `true` zu sehen.
```

2020-10-10 07:59 UTC, anarchuser commented on spiele/blokus/xml-dokumentation/zuege-senden.adoc
> +Wird zusätzlich `FLIPPED` auf `true` gesetzt, so werden die von der Rotation resultierenden Koordinaten noch auf der X-Achse invertiert. `(x, y) => (-x, y)`
```suggestion
Wird zusätzlich `FLIPPED` auf `true` gesetzt, so werden die von der Rotation resultierenden Koordinaten anschließend noch auf der X-Achse invertiert. `(x, y) => (-x, y)`
```
Es ist wichtig zu wissen, dass erst rotiert und dann geflippt wird

2020-10-10 07:59 UTC, anarchuser commented on spiele/blokus/xml-dokumentation/zuege-senden.adoc
> +Nach den Transformationen werden die Kooridnaten noch normalisiert, indem sie mit dem minimalen X wert aller Koordinaten und dem minimalen Y wert aller Koordinaten subtrahiert werden. `(x, y) => (x -
```suggestion
Nach den Transformationen werden die Koordinaten noch normalisiert, d.h. sie werden an die obere linke Ecke angelegt.
Effektiv werden sie mit dem minimalen X Wert aller Koordinaten und dem minimalen Y Wert aller Koordinaten subtrahiert. `(x, y) => (x - minX, y - minY)` 
```

2020-10-10 07:59 UTC, anarchuser commented on spiele/blokus/xml-dokumentation/zuege-senden.adoc
> +Schließlich werden die Koordinaten noch mit den `X, Y` Werten, die zum Move gehören addiert um die Koordinaten aller Teile des Spielsteins auf dem Board zu erhalten.
```suggestion
Schließlich werden die Koordinaten noch mit den `X, Y` Werten, die zum Move gehören, addiert, um die Koordinaten aller Teile des Spielsteins auf dem Board zu erhalten.
```

2020-10-10 07:59 UTC, anarchuser commented on spiele/blokus/xml-dokumentation/zuege-senden.adoc
> +Schließlich werden die Koordinaten noch mit den `X, Y` Werten, die zum Move gehören addiert um die Koordinaten aller Teile des Spielsteins auf dem Board zu erhalten.
Sollten `Move` und `Board` nicht auch eher auf deutsch sein?
Also z.B. `Zug` und `Spielfeld`

2020-10-10 07:59 UTC, anarchuser commented on spiele/blokus/xml-dokumentation/zuege-senden.adoc
> +Nach den Transformationen werden die Kooridnaten noch normalisiert, indem sie mit dem minimalen X wert aller Koordinaten und dem minimalen Y wert aller Koordinaten subtrahiert werden. `(x, y) => (x -
Es hilft den Schülern vielleicht, sich das so besser vorzustellen

2020-10-11 11:19 UTC, niklasCarstensen commented
Danke die bau ich gleich ein und merge dann

2020-10-11 14:59 UTC, niklasCarstensen commented on spiele/blokus/xml-dokumentation/zuege-senden.adoc
> +Schließlich werden die Koordinaten noch mit den `X, Y` Werten, die zum Move gehören addiert um die Koordinaten aller Teile des Spielsteins auf dem Board zu erhalten.
Da es die XML Doku ist würde ich hier direkt auf die Typen eingehen

2020-10-11 15:13 UTC, niklasCarstensen commented on spiele/blokus/xml-dokumentation/zuege-senden.adoc
> +Schließlich werden die Koordinaten noch mit den `X, Y` Werten, die zum Move gehören addiert um die Koordinaten aller Teile des Spielsteins auf dem Board zu erhalten.
Aber ich würde es sonst ändern wenn ich überstimmt werde ^^'

2020-10-11 15:16 UTC, merged